[workspace]

members = [
  "exp-epa",
  "cwf-theory",
  "eqlog",
  "eqlog-runtime",
  "eqlog-test",
	"v1_to_v2",
  "examples/inference",
]

# Keep examples out of workspace. It should be possible to build them without a
# local eqlog checkout.
exclude = [
  "examples/semilattice",
]
