[workspace]

members = [
  "eqlog",
  "eqlog-runtime",
  "eqlog-test",
	"v1_to_v2",
  "examples/inference",
  "eqlog-eqlog",
]

# Keep examples out of workspace. It should be possible to build them without a
# local eqlog checkout.
exclude = [
  "examples/semilattice",
	"cwf-theory",
	"exp-epa",
]
