[package]
name = "eqlog"
version = "0.1.0"
edition = "2021"
authors = [
  "Martin E. Bidlingmaier <martin.bidlingmaier@mbid.me>",
  "Jakob Botsch Nielsen <jakob.botsch.nielsen@gmail.com>",
]
license = "MIT"
description = "Datalog with equality"
repository = "https://github.com/eqlog/eqlog/"
readme = "../README.md"

[dependencies]
lalrpop-util = { version = "0", features = [ "lexer" ] }
regex = "1"
maplit = "1"
itertools = "0"
convert_case = "0"
indoc = "1"

[build-dependencies]
lalrpop = { version = "0", features = [ "lexer" ] }
