[package]
name = "cwf-theory"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.eqlog-util]
path = "../eqlog/eqlog-util"

[build-dependencies.eqlog]
path = "../eqlog"
